[package]
name = "shieldvoucher"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.16.0"
integrity = "2.0.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.57.0" }

[[target.starknet-contract]]
sierra = true
casm = true
